### PR TITLE
fix: fixed a bug in that words with multiple identical letters would be marked as only partially-correct

### LINKED ISSUE #90: Liedle incorrectly colours tiles for words with repeated letters
**Description**
Liedle incorrectly colours tiles for words with repeated letters. More specifically, only the first occurrence of the repeated letters is coloured correctly, the rest are coloured yellow. This happens when the word guessed is incorrect or correct so is not a product of the 8% lie rate (correct guesses should always be fully coloured green). 

**Steps to reproduce**
This bug happens with certain words so we will need to modify the code 
- Find `liedle/index.js`
- Replace the line `import { dictionary } from './dictionary.js'` with `const dictionary = ['happy']` 
- Visit `http://localhost:1234/liedle/index.html` and close the help dialogue
- Type `happy`

**Expected behaviour**
All letters should be green because the whole word is correct. The game should also end. 

**Actual behaviour**
The 4th letter (2nd P) is yellow. The game does end as expected. 
image

**Potential cause**
The function `colourLetter(tile)` looks for the index of the first occurence of the letter which might be different to its actual position. 

**Potential fix**
Use `secretWord.charAt(tile.dataset.colIndex) === tile.innerHTML` to check if the letter is the right letter and is in the right position.

### PR DESCRIPTION
**Pull request by JosiahBull**
## Todo
- [x] add test to validate failure condition
- [x] fix bug by updating the `colourLetter()` and `colourLetterFalsely()` functions

## Motivation

Liedle incorrectly colours tiles for words with repeated letters. More specifically, only the first occurrence of the repeated letters is coloured correctly, the rest are coloured yellow.

## Summary of changes

- Tests added to validate that when entering a word like `hello` all letters are marked as green for correct
- `liedle/index.js` updated function to check the char at the correct index, instead of getting the first occurrence

## Attached GitHub issue

Closes #90 

### Local Build
- [x] Ran all local tests `npm run test:ci`
- [x] Manually tested my solution

### GitHub
- [x] Target branch has been set correctly
- [x] PR has been rebased onto target branch
- [x] PR has been assigned an owner
- [x] Author has performed a self-review of the code
- [x] Removed the WIP message from the top of this PR

### CODE REVIEW

File: src/liedle/index.js [hunk 1]
```diff
@@ -156,38 +156,28 @@ function colourWord(word) {
...
-      type = Math.random() < 0.5 ? "wrong" : "right-letter";
-      break;
-    default:
-      type = Math.random() < 0.5 ? "right" : "wrong";
-      break;
+  let testChar = tile.innerHTML.toLowerCase();
+  if (secretWord.charAt(tile.dataset.colIndex) === testChar) {
+    tile.dataset.type =  Math.random() < 0.5 ? "wrong" : "right-letter";
+  } else if (secretWord.includes(testChar)) {
+    tile.dataset.type = Math.random() < 0.5 ? "right" : "wrong";;
```
Comment (lche262) [inline src/liedle/index.js:174]: Unnesscery ";" at the end of the line, it is trivial and you can merge without changing it. Just a suggestion :)

**Review by lche262 — APPROVED** [review]
Nice work! Ran and tested on my machine with no issue found
