### PR TITLE
Check mergeable tiles in check lose

### LINKED ISSUE #99: 2048 Expert game ends prematurely when board is full but still contains possible merges
**Description**
The game finishes prematurely when the board is filled up rather than when there are no more possible merges. The final message appears and the game is restarted.

**Steps to reproduce**

1. Find `2048-expert/index.js`
2. Add the following to the end of the file
```
for (let i = 0; i < 36; i=i+4) {
    cells[i].innerHTML = 2;
    cells[i+1].innerHTML = 4;
    cells[i+2].innerHTML = 4;
    cells[i+3].innerHTML = 2;
  }
addColours()
```
3. Run `npm start`
4. Visit `http://localhost:1234/2048-expert/index.html`
(Page should look like this)
image

5. Press the down or up button

**Expected behaviour**
Game should still continue, the left and right buttons can be pressed to merge remaining tiles

**Actual behaviour**
Game ends and losing message shows up

**Potential cause**
`checkLost()` checks for empty cells rather than if any cells can still be merged

### PR DESCRIPTION
**Pull request by lche262**
## Todo
- [x] add test to validate failure condition
- [x] fix bug by adding check conditions on checkLost() function

## Motivation

Players should continue the game even if the board is filled but merging is possible. Once the tiles are merged, we created more space for new tiles to generate

## Summary of changes

- Tests were added to check if the game still stops when the board is full but merging is possible 
- `2048expert/index.js` adding checking conditions on checklost function for detecting mergeable tiles

## Attached GitHub issue

Closes #99

### Local Build
- [x] Ran all local tests `npm run test:ci`
- [x] Manually tested my solution

### GitHub
- [x] Target branch has been set correctly
- [x] PR has been rebased onto target branch
- [x] PR has been assigned an owner
- [x] Author has performed a self-review of the code
- [x] Removed the WIP message from the top of this PR

### CODE REVIEW

File: src/2048-expert/index.js [hunk 1]
```diff
@@ -28,7 +28,9 @@ function generateNewTile() {
   } else {
     // if a cell is already has a number, then find a new tile
     checkLost();
-    generateNewTile();
+    if(!checkisFull()){
+      generateNewTile();
+    }
```
Comment (JosiahBull) [inline src/2048-expert/index.js:33]: Doesn't calling `checkLost()` implicitly do this check already?

File: src/2048-expert/index.js [hunk 2]
```diff
@@ -187,6 +189,7 @@ function keyUpLeft() {
   moveLeft();
   generateTwoNewTile();
   addColours();
+  checkLost();
```
Comment (JosiahBull) [inline src/2048-expert/index.js:192]: Why are we calling `checkLost()` after it's already been called as part of `mergeHorizontal()`? It will also be called as part of `generateTwoNewTile()` if required.

File: src/2048-expert/index.js [hunk 3]
```diff
@@ -223,18 +229,38 @@ function checkWin() {
...
 
-// a loss happens when all cells are full
+// a loss happens when all cells are full and they are not mergeable 
 function checkLost() {
+  if (checkisFull()) {
+    // check if any tiles are mergeable
+    for (let i = 0; i < totalCell-6; i++) {
+      // check vertical
+      if((cells[i].innerHTML == cells[i+6].innerHTML)){
+        // the user did not lose the game
```
Comment (JosiahBull) [inline src/2048-expert/index.js:239]: don't we need to check that at least **two** cells are mergable for them to not lose the game?

File: src/2048-expert/index.js [hunk 4]
```diff
@@ -223,18 +229,38 @@ function checkWin() {
   }
 }
 
-// a loss happens when all cells are full
+// a loss happens when all cells are full and they are not mergeable 
 function checkLost() {
+  if (checkisFull()) {
+    // check if any tiles are mergeable
+    for (let i = 0; i < totalCell-6; i++) {
+      // check vertical
```
Comment (JosiahBull) [inline src/2048-expert/index.js:237]: Can we reuse the `mergeHorizontal()` and `mergeVertical()` functions here? Unsure...

**Review by JosiahBull — CHANGES_REQUESTED** [review]
~~Honestly, I think this issue should be closed without being merged.~~

~~In the game logic, it calls~~
~~`moveLeft/Right/Up/Down()`~~
~~`mergeHorizontal/Vertical()`~~
~~`moveLeft/Right/Up/Down()`~~
~~`generateTwoNewTile()`~~

~~Therefore, if there were any mergable tiles they should have been merged already at the `mergeHorizontal/Vertical()` step of the application - and if there aren't enough spaces for new tiles to be generated at that point the failure condition has been reached.~~

~~So imo this functionality already exists, and we can close the issue and this PR.~~

Nvm, yeah I can see how this can happen, didn't read the original issue closely enough. There is a case to be made that if a user has a valid move left, and they made an invalid move by mistake that they should be punished for that instead of allowed to try again, but that's a bit of a different discussion.

File: src/2048-expert/index.js (hunk 1 above)
Comment (lche262) [reply src/2048-expert/index.js:33]: checkLost() check the block is full to make winning/ losing condition. Therefore if the checkLost() decides that the game is still playable, the game will continue and generateNewTile() will occur. However, when you call genertareNewTile() with no space on the board, an error occurs for creating a new tile that exceeds the space.

Comment (JosiahBull) [reply src/2048-expert/index.js:33]: I think there is an edge case where we'd only generate 1 tile that should be addressed. Either we spawn both tiles or no tiles imo.

Comment (JosiahBull) [reply src/2048-expert/index.js:33]: If we'd prefer to spawn as many as we can then that would be valid too, entirely a matter of opinion. Will mark this as resolved as it's not really important.

File: src/2048-expert/index.js (hunk 2 above)
Comment (lche262) [reply src/2048-expert/index.js:192]: Sometimes this could happen when the board is completely full but still playable, it will be a minor difference but I'm more intent to encourage the player to not give up all the possibilities for winning the game/ getting a higher score. I think it is more reasonable to check it after every move player makes.

File: src/2048-expert/index.js (hunk 4 above)
Comment (JosiahBull) [reply src/2048-expert/index.js:237]: After rereading the issue, this comment isn't relevant as we don't want to attempt to merge the blocks at this point.

File: src/2048-expert/index.js (hunk 3 above)
Comment (lche262) [reply src/2048-expert/index.js:239]: It depends on how we want to implement the game. If the game is still playable after no empty cells are left, I think the game can continue to be played after one block left as well.

File: src/2048-expert/index.js (hunk 2 above)
Comment (JosiahBull) [reply src/2048-expert/index.js:192]: I don't think we need the extra call to `checkLost()` though?

Comment (JosiahBull) [reply src/2048-expert/index.js:192]: The loss condition won't have been activated between the `mergeHorizontal/Vertical()` call and this second call afaict.

Comment (JosiahBull) [reply src/2048-expert/index.js:192]: Oh, jk, yeah. Could have 2 free tiles left after `mergeHorizontal`, they both get filled by `generateTwoNewTile()`, and neither can be merged - which would theoretically end the game.

**Review by JosiahBull — APPROVED** [review]
